import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Raghul',
      email: 'raghul2521@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Test',
      email: 'test@user.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  dishes: [
    {
      name: 'Burger',
      slug: 'burger',
      category: 'Fast Food',
      image: '/images/burger.jpeg',
      price: 100,
      cuisine: 'American',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Tasty grilled burger',
    },
    {
      name: 'Pizza',
      slug: 'pizza',
      category: 'Fast Food',
      image: '/images/pizza.jpeg',
      price: 200,
      cuisine: 'Italian',
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      description: 'Tasty cheesy',
    },
    {
      name: 'Taco',
      slug: 'taco',
      category: 'Fast Food',
      image: '/images/taco.jpeg',
      price: 90,
      cuisine: 'Mexican',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Tasty Spicy Taco',
    },
    {
      name: 'Chicken Biriyani',
      slug: 'chicken-biriyani',
      category: 'Main Course',
      image: '/images/biriyani.jpeg',
      price: 300,
      cuisine: 'Indian',
      rating: 4.9,
      numReviews: 10,
      countInStock: 30,
      description: 'Tasty spicy biriyani',
    },
    {
      name: 'Mushroom Noodles',
      slug: 'mushroom-noodles',
      category: 'Main Course',
      image: '/images/noodles.jpeg',
      price: 250,
      cuisine: 'Chinese',
      rating: 3.7,
      numReviews: 10,
      countInStock: 20,
      description: 'Tasty good noodles',
    },
    {
      name: 'Paneer Tikka',
      slug: 'paneer-tikka',
      category: 'Starters',
      image: '/images/paneer.jpeg',
      price: 340,
      cuisine: 'Indian',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Hot grilled paneer',
    },
  ],
};

export default data;
